apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        insecure-skip-tls-verify: true
        server: https://indexer-kube-apiserver.kube-system.svc:6443
      name: default
    contexts:
    - context:
        cluster: default
        user: admin
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users:
    - name: admin
      user:
        client-certificate-data: <client cert data>
        client-key-data: <client key data>
kind: ConfigMap
metadata:
  annotations:
    managedBy: https://github.com/deyiyao/indexer-benchmark
  labels:
    sync.controller.federation.tess.io/watch: "true"
  name: indexer-kubeconfig
