apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        insecure-skip-tls-verify: true
        server: https://kube-apiserver.kube-system.svc:6443
      name: default
    contexts:
    - context:
        cluster: default
        user: admin
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users:
    - name: admin
      user:
        client-certificate-data: <client-certificate-data>
        client-key-data: <client-key-data>
kind: ConfigMap
metadata:
  name: kube-apiserver-kubeconfig
  namespace: kube-system